#!/bin/bash
# generates some messages for Crusoe

# generate the fake data and store in a variable
node fakeDataGenerator.js
fakeData=$(<generatedData.js)
result=''

# generate series of insert commands to pass to db
  for data in $fakeData
    do
      # change - to space
      mod=${data//!/ }
      result+='db.messages.insert('$mod$');\n'
    done

echo the fake data:
echo $result

# place commands in a file to be fed to meteor mongo
touch meteorCommands.txt
echo $result > meteorCommands.txt
echo "exit" >> meteorCommands.txt

# access the production db for cruose420
meteor mongo crusoe.meteor.com<meteorCommands.txt
